import { useContext, useState } from 'react';
import { PaperAirplaneIcon, SparklesIcon, ArrowDownTrayIcon } from '@heroicons/react/24/solid';
import { ProductsContext } from '../../../contexts/ProductsContext';
import { GoogleGenAI, Modality } from "@google/genai";


function ExtraFormImage({ formData, handleValidationData, resultImage, setResultImage }) {
  const { productsByIDState } = useContext(ProductsContext);
  const ai = new GoogleGenAI({ apiKey: import.meta.env.VITE_GEMINI_API_KEY });

  const [inputValue, setInputValue] = useState('');
  const [resultImageText, setResultImageText] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [dropDownOpen, setDropdownOpen] = useState(false);

  const templatePrompts = [
    "Tempat Wedding tema klasik elegan",
    "Dekorasi pernikahan outdoor di taman",
    "Desain kartu undangan bernuansa emas",
  ];

  const formDataText = formData ? `\nData Pelanggan:\n${JSON.stringify(formData, null, 2)}` : "";
  const productDataText = productsByIDState ? `\nData Paket:\n${JSON.stringify(productsByIDState, null, 2)}` : "";
  const contents = `Buatkan gambar "${inputValue}" dengan budget ${productsByIDState?.price || 0} dari data berikut ini:
  ${formDataText}
  ${productDataText}`;

  // ====================================================================================================================================

  const handleGenerateAIImageWithPrompt = async () => {
    setIsLoading(true);
    setResultImage(null);
    setResultImageText(null);

    try {
      const response = await ai.models.generateContent({
        model: "gemini-2.0-flash-preview-image-generation",
        contents: contents,
        config: { responseModalities: [Modality.TEXT, Modality.IMAGE] },
      });

      for (const part of response.candidates[0].content.parts) {
        if (part.text) {
          setResultImageText(part.text)
        } else if (part.inlineData) {
          const imageData = part.inlineData.data;
          const imageSrc = `data:image/png;base64,${imageData}`;
          setResultImage(imageSrc);
        }
      }

    } catch (error) {
      console.error("Gagal generate prompt:", error);
    } finally {
      setIsLoading(false);
    }
  };

  // ====================================================================================================================================

  return (
    <div className="relative">


      {dropDownOpen && (
        <div className="absolute right-0 bottom-full mb-2 z-20 w-96 shadow-xl rounded-xl bg-base-100">

          {/* Header */}
          <section className="bg-error p-3 rounded-t-xl">
            <h1 className="text-base-100 font-bold">Generate Prompt Gambar</h1>
          </section>

          <section className="p-3 min-h-[200px] relative">
            {isLoading && (
              <div className="absolute inset-0 bg-white/70 backdrop-blur-sm flex justify-center items-center rounded-xl z-10">
                <span className="loading loading-spinner loading-lg text-error"></span>
              </div>
            )}

            {/* Template Buttons */}
            <div className="grid gap-2 mb-4">
              {templatePrompts.map((template, i) => (
                <button
                  key={i}
                  className="btn btn-sm"
                  onClick={async (e) => {
                    e.preventDefault();
                    setInputValue(template);
                    handleValidationData()
                    await handleGenerateAIImageWithPrompt();
                  }}
                  disabled={isLoading}
                >
                  {template}
                </button>
              ))}
            </div>

            {/* Input manual */}
            <div className="join w-full">
              <input
                type="text"
                value={inputValue}
                onChange={(e) => setInputValue(e.target.value)}
                placeholder="Masukkan tema atau konsep..."
                className="input input-bordered join-item w-full"
                disabled={isLoading}
              />
              <button
                className="btn btn-error join-item"
                onClick={async (e) => {
                  e.preventDefault();
                  handleValidationData()
                  await handleGenerateAIImageWithPrompt();
                }}
                disabled={!inputValue || isLoading}
              >
                <PaperAirplaneIcon className="w-5 h-5" />
              </button>
            </div>

            {/* Result */}

            {!isLoading && resultImage && (
              <div className="mt-4 border border-base-300 rounded-xl p-4 max-h-96 overflow-y-auto grid gap-4">

                <div className="relative">
                  {/* Hasil Image AI */}
                  <img className="rounded-xl w-full object-cover max-h-64"
                    src={resultImage}
                    alt="Generated by AI"
                    onClick={() => document.getElementById(`image_ai_modal`).showModal()}
                  />

                  {/* Tombol Download */}
                  <a className="absolute right-1 top-1 btn btn-sm px-2 bg-neutral text-base-100"
                    href={resultImage}
                    download="generated-image.png"
                  ><ArrowDownTrayIcon className="h-5 w-5 animate-bounce" /></a>

                  {/* Modal Review Gambar */}
                  <dialog id={`image_ai_modal`} className="modal modal-bottom sm:modal-middle">
                    <div className="modal-box p-0">
                      <img src={resultImage} alt={`Preview Gambar`} className="w-full max-h-full object-contain rounded-t" />
                      <a className="absolute right-1 top-1 btn btn-sm px-2 bg-neutral text-base-100"
                        href={resultImage}
                        download="generated-image.png"
                      ><ArrowDownTrayIcon className="h-5 w-5 animate-bounce" /></a>
                    </div>
                    <form method="dialog" className="modal-backdrop">
                      <button>close</button>
                    </form>
                  </dialog>
                </div>

                {/* Deskripsi AI Gambar */}
                <div className="collapse bg-base-100 border-base-300 border">
                  <input type="checkbox" />
                  <div className="collapse-title font-semibold skeleton bg-base-200">Deskripsi Hasil Gambar AI</div>
                  <div className="collapse-content text-justify">
                    <label>{resultImageText}</label>
                  </div>
                </div>

                <label>Download gambar diatas dan upload ke dalam form, jika belum sesuai anda bisa generate gambari ulang</label>
              </div>
            )}


          </section>
        </div>
      )}

      {/* Toggle Button */}
      <button className="btn m-1 bg-neutral text-base-100" type="button" onClick={(e) => {
        e.preventDefault();
        setDropdownOpen(!dropDownOpen)
      }}>
        <div className="animate-bounce">
          <SparklesIcon className="h-5 w-5 animate-pulse" />
        </div>
      </button>
    </div>
  );
}

export default ExtraFormImage;
